import { afterAll, beforeAll, describe, expect, it, vi } from "vitest";
import { createTestDatabase, hasTestDatabase, insertCourseProduct, insertMember, insertOffer, insertOrder } from "../testing/db";
const transport = vi.hoisted(() => ({ messages: [] as any[], fail: false }));
vi.mock("../email/mailer", () => ({ sendMail: vi.fn(async (message: any) => { if (transport.fail) return { sent:false,error:"ZZ temporary outage" }; transport.messages.push(message); return { sent:true }; }) }));
const describeDb = hasTestDatabase ? describe : describe.skip;
describeDb("purchase gifting (integration)", () => {
  let db: Awaited<ReturnType<typeof createTestDatabase>>;
  let fulfillment: typeof import("./fulfillment");
  let gift: typeof import("./purchaseGift");
  let access: typeof import("./access");
  beforeAll(async () => {
    db = await createTestDatabase("purchase_gift");
    process.env.DATABASE_URL = db.url; process.env.JWT_SECRET = "ZZ-gift-secret";
    fulfillment = await import("./fulfillment"); gift = await import("./purchaseGift"); access = await import("./access");
  }, 60000);
  afterAll(async () => { await (await import("../db/pool")).pool.end(); await db?.drop(); });
  it("keeps receipt ownership with payer and grants main product plus bump only to recipient, once", async () => {
    const payer = await insertMember(db.client, "sagar+zz-gift-payer@callsphere.ai");
    const product = await insertCourseProduct(db.client, "zz-gift-main");
    const bump = await insertCourseProduct(db.client, "zz-gift-bump");
    const offerId = await insertOffer(db.client, "zz-gift-offer", [product.productId]);
    const orderId = await insertOrder(db.client, {offerId,memberId:payer,email:"sagar+zz-gift-payer@callsphere.ai",totalCents:2700});
    await db.client.query(`UPDATE orders SET gift_recipient_email=$2,gift_message=$3 WHERE id=$1`,[orderId,"sagar+zz-gift-recipient@callsphere.ai","ZZ A gift <script>bad</script>"]);
    await db.client.query(`INSERT INTO order_items(order_id,product_id,title,kind,quantity,unit_cents,amount_cents) VALUES($1,$2,'ZZ bump','bump',1,0,0)`,[orderId,bump.productId]);
    expect((await fulfillment.fulfillPayment({orderId,amountCents:2700})).fulfilled).toBe(true);
    const order = (await db.client.query(`SELECT member_id,gift_member_id,gift_created_member FROM orders WHERE id=$1`,[orderId])).rows[0];
    expect(order.member_id).toBe(payer); expect(order.gift_member_id).not.toBe(payer); expect(order.gift_created_member).toBe(true);
    expect(await access.hasProductAccess(payer,product.productId)).toBe(false);
    expect(await access.hasProductAccess(order.gift_member_id,product.productId)).toBe(true);
    expect(await access.hasProductAccess(order.gift_member_id,bump.productId)).toBe(true);
    expect((await db.client.query(`SELECT count(*)::int AS n FROM jobs WHERE kind='purchase.gift' AND payload->>'orderId'=$1`,[String(orderId)])).rows[0].n).toBe(1);
    expect((await fulfillment.fulfillPayment({orderId,amountCents:2700})).fulfilled).toBe(false);
    transport.fail = true;
    await expect(gift.deliverGiftById(orderId)).rejects.toThrow("ZZ temporary outage");
    expect((await db.client.query(`SELECT gift_delivered_at FROM orders WHERE id=$1`,[orderId])).rows[0].gift_delivered_at).toBeNull();
    transport.fail = false;
    await Promise.all([gift.deliverGiftById(orderId),gift.deliverGiftById(orderId)]);
    expect(transport.messages).toHaveLength(1);
    expect(transport.messages[0].to).toBe("sagar+zz-gift-recipient@callsphere.ai");
    expect(transport.messages[0].html).toContain("&lt;script&gt;");
    expect(transport.messages[0].html).not.toContain("<script>");
    expect(transport.messages[0].text).toContain("set-password");
    expect((await db.client.query(`SELECT gift_delivered_at FROM orders WHERE id=$1`,[orderId])).rows[0].gift_delivered_at).not.toBeNull();
    const refund = await fulfillment.recordRefund({orderId,amountCents:2700,revokeAccessOnFullRefund:true,stripeRefundId:"ZZ-refund"});
    expect(refund).toMatchObject({recorded:true,fullyRefunded:true,revokedCount:2});
    expect(await access.hasProductAccess(order.gift_member_id,product.productId)).toBe(false);
    expect(await access.hasProductAccess(order.gift_member_id,bump.productId)).toBe(false);
  });
});
