import { motion } from "motion/react";
import { Seo } from "@/components/Seo";
import { LuxePageHero } from "@/components/luxe/LuxePageHero";
import { Section } from "@/components/luxe/Section";
import { useEntranceMotion } from "@/hooks/useEntranceMotion";
import { cn } from "@/lib/cn";

const EASE: [number, number, number, number] = [0.22, 1, 0.36, 1];
const VIEWPORT = { once: true, margin: "-10% 0px -6% 0px" } as const;

/* Reproduced verbatim from bossclinician.com/financialdisclaimer, in order.
   The document is set in upper case on the live site and stays that way. */
const PARAGRAPHS: string[] = [
  "WITH REGARDS TO FINANCIAL CONTENT ON THE SITE:",
  "THE SITE EXISTS FOR EDUCATIONAL PURPOSES ONLY, AND THE MATERIALS AND INFORMATION CONTAINED THEREIN ARE FOR GENERAL INFORMATIONAL PURPOSES ONLY. WITH REGARD TO FINANCIAL CONTENT CONTAINED THEREIN: NEITHER COMPANY NOR ITS OWNERS, OFFICERS, DIRECTORS, EMPLOYEES, SUBSIDIARIES, AFFILIATES, LICENSORS, SERVICE PROVIDERS, CONTENT PROVIDERS AND AGENTS ARE FINANCIAL ADVISORS, OR AN INVESTMENT ADVISORY SERVICE, AND NOTHING CONTAINED IN THE SITE IS INTENDED TO BE OR TO BE CONSTRUED AS FINANCIAL ADVICE, OR LEGAL, COMPLIANCE, FINANCIAL, TAX, ACCOUNTING OR RELATED ADVICE.",
  "THE INFORMATION CONTAINED ON THE SITE IS BASED ON SOURCES AND INFORMATION REASONABLY BELIEVED TO BE ACCURATE AS OF THE TIME IT WAS RECORDED OR CREATED. HOWEVER, THIS MATERIAL DEALS WITH TOPICS THAT ARE CONSTANTLY CHANGING AND ARE SUBJECT TO ONGOING CHANGES RELATED TO TECHNOLOGY AND THE MARKET PLACE AS WELL AS LEGAL AND RELATED COMPLIANCE ISSUES. THEREFORE, THE COMPLETENESS AND CURRENT ACCURACY OF THE IN THE SITE CANNOT BE GUARANTEED.",
  "THE EDUCATION AND INFORMATION PRESENTED ON THE SITE IS INTENDED FOR A GENERAL AUDIENCE AND DOES NOT PURPORT TO BE, NOR SHOULD IT BE CONSTRUED AS, SPECIFIC ADVICE TAILORED TO ANY INDIVIDUAL. YOU, AS AN END USER OF THIS INFORMATION MAY THEREFORE USE THIS CONTENT AS A GENERAL GUIDELINE AND NOT AS THE ULTIMATE SOURCE OF CURRENT INFORMATION AND WHEN APPROPRIATE, YOU UNDERSTAND THAT YOU SHOULD CONSULT MY OWN LEGAL, ACCOUNTING OR OTHER ADVISORS.",
  "ANY CASE STUDIES, EXAMPLES, ILLUSTRATIONS, OR TESTIMONIALS CANNOT GUARANTEE THAT YOU WILL ACHIEVE SIMILAR RESULTS. IN FACT, YOUR RESULTS MAY VARY SIGNIFICANTLY AND FACTORS SUCH AS MY MARKET, PERSONAL EFFORT AND MANY OTHER CIRCUMSTANCES MAY AND WILL CAUSE RESULTS TO VARY.",
  "YOUR USE OF THE INFORMATION CONTAINED HEREIN IS AT YOUR OWN RISK. IT IS YOUR RESPONSIBILITY TO EVALUATE THE ACCURACY, COMPLETENESS OR USEFULNESS OF ANY INFORMATION, OPINION, ADVICE OR OTHER CONTENT CONTAINED IN THE SITE. YOU WILL SEEK THE ADVICE OF PROFESSIONALS, AS APPROPRIATE, REGARDING THE EVALUATION OF ANY SPECIFIC INFORMATION, OPINION, ADVICE OR OTHER CONTENT.",
  "ANY AND ALL CLAIMS OR REPRESENTATIONS, AS TO INCOME EARNINGS ON THE SITE, ARE NOT TO BE CONSIDERED AS AVERAGE EARNINGS. THERE CAN BE NO ASSURANCE THAT ANY PRIOR SUCCESSES, OR PAST RESULTS, AS TO INCOME EARNINGS, CAN BE USED AS AN INDICATION OF YOUR FUTURE SUCCESS OR RESULTS.",
  "MONETARY AND INCOME RESULTS ARE BASED ON MANY FACTORS. COMPANY HAS NO WAY OF KNOWING HOW WELL YOU WILL DO, AS THEY DO NOT KNOW YOU, YOUR BACKGROUND, YOUR WORK ETHIC, OR YOUR BUSINESS SKILLS OR PRACTICES. THEREFORE, COMPANY DOES NOT GUARANTEE OR IMPLY THAT YOU WILL GET RICH, THAT YOU WILL DO AS WELL, OR THAT YOU WILL MAKE ANY MONEY AT ALL. IF YOU RELY UPON FIGURES PROVIDED IN THE SITE; YOU MUST ACCEPT THE RISK OF NOT DOING AS WELL.",
];

export default function FinancialDisclaimer() {
  const reduce = useEntranceMotion();

  return (
    <>
      <Seo
        title="Financial Disclaimer for Boss Clinician | Important Information"
        description="Read our Financial Disclaimer for important information on educational content. It’s not financial, legal, or tax advice. Use at your own risk."
      />

      <LuxePageHero eyebrow="Legal" title="Financial Disclaimer" tone="green" />

      <Section surface="base" space="md" aria-label="Financial Disclaimer">
        <motion.article
          className="mx-auto max-w-[70ch] space-y-5"
          initial={reduce ? false : { opacity: 0, y: 22 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={VIEWPORT}
          transition={{ duration: 0.7, ease: EASE }}
        >
          {PARAGRAPHS.map((paragraph, i) => (
            <p
              key={i}
              className={cn(
                "copy-luxe text-pretty break-words tracking-[0.02em]",
                // The document's own opening line, which frames everything under it.
                i === 0 && "text-white",
              )}
            >
              {paragraph}
            </p>
          ))}
        </motion.article>
      </Section>
    </>
  );
}
