import type { Resource } from "@/types";

export const resources: Resource[] = [
  {
    id: "r-masterclass",
    slug: "free-masterclass",
    title: "The 4-Step Blueprint to Building a Profitable Private Practice",
    description:
      "This FREE masterclass breaks it all down for you. You'll learn a simple 4-step framework to start or grow your private practice with more confidence and less chaos. No guesswork. No overwhelm.",
    image: "/images/24ea3347f734.png",
    ctaLabel: "Watch Free Masterclass",
    ctaUrl: "/apply",
    kind: "masterclass",
    sort: 1,
    published: true,
  },
  {
    id: "r-insurance-guide",
    slug: "insurance-or-superbills-guide",
    title: "Insurance or Superbills? Free Guide",
    description: "Want to know if you should take insurance or accept superbills in your practice?",
    image: "/images/a1a700d17e27.png",
    ctaLabel: "Download the Guide",
    ctaUrl: "/apply",
    kind: "guide",
    sort: 2,
    published: true,
  },
  {
    id: "r-starter-guide",
    slug: "private-practice-starter-guide",
    title: "Private Practice Starter Guide",
    description: "Just starting your practice or want to make sure you start on the right path?",
    image: "/images/8f0e57f6fbb3.jpg",
    ctaLabel: "Download Guide",
    ctaUrl: "/apply",
    kind: "guide",
    sort: 3,
    published: true,
  },
  {
    id: "r-planner-checklist",
    slug: "profitable-practice-planner",
    title: "Profitable Practice Planner Checklist",
    description: "Grab the must-have profitable practice planner now.",
    image: "/images/f6e8f514c85a.png",
    ctaLabel: "Download Checklist",
    ctaUrl: "/apply",
    kind: "checklist",
    sort: 4,
    published: true,
  },
  {
    id: "r-income-estimator",
    slug: "private-client-income-estimator",
    title: "Private Client Income Estimator",
    description:
      "Calculate your income potential — see exactly what your practice could generate based on your session rate and caseload.",
    image: "/images/26729b8c6ec0.png",
    ctaLabel: "Estimate My Income",
    ctaUrl: "/apply",
    kind: "tool",
    sort: 5,
    published: true,
  },
  {
    id: "r-business-plan-guide",
    slug: "private-practice-business-plan-guide",
    title: "Private Practice Business Plan Guide",
    description:
      "Download the free Private Practice Business Plan Guide and map out your vision, goals, and structure for a profitable practice — before you start, scale, or expand.",
    image: "/images/87860f443ed2.png",
    ctaLabel: "Download the Guide",
    ctaUrl: "/apply",
    kind: "guide",
    sort: 6,
    published: true,
  },
];
